<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MajorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('majors')->insert([
            ['name' => 'Akuntansi', 'trans-name'=> 'Accounting', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Studying accounting includes learning about financial accounting—the reporting of an organization's financial information—and managerial accounting—the use of that data to measure the entity's performance and inform decisions about its future and controls. An accounting major learns how companies' and other organizations' financial records are prepared and maintained. He or she studies taxation, auditing, and financial reporting. ", 'img' => 'akuntansi.jpg'],

            ['name' => 'Biologi', 'stream-science' => '1', 'trans-name'=> 'Biology', 'stream-social' => '0', 'description' => "Biology majors study the behavior, classification, and evolution of living entities called organisms. This natural science encompasses specialties such as microbiology, marine biology, ecology, zoology, physiology, cellular and molecular biology, and botany. Students can earn Associate, Bachelor's, Masters and Doctorate degrees. After earning an undergraduate or graduate degree in biology, some students enter professional health science programs including those in medicine, dentistry, podiatry, optometry, and veterinary science. ", 'img' => 'biologi.jpg'],

            ['name' => 'Farmasi', 'trans-name'=> 'Pharmacy', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Pharmacists fill patient prescriptions for drugs and explain how to use them. As consumers become more educated about health products and have more questions about the treatments physicians prescribe for them, it falls upon the pharmacist to supply the attention and advice the medical consumer desires.

            In institutional settings, pharmacists are an integral part of the total healthcare team. No longer do they occupy the basement office, filling prescriptions and answering the occasional question from the physician. The expertise of the pharmacist helps to support physicians and establish policies as drug therapies become more and more complicated.", 'img' => 'farmasi.jpg'],

            ['name' => 'Fisika', 'trans-name'=> 'Physics', 'stream-science' => '1', 'stream-social' => '0', 'description' => "A physics major is a science degree path that helps explain how the world works and how the universe is structured. Majors study matter and energy and gain exposure to both classical and modern theories in the field. Students also spend time completing experiments in a lab setting. With the scale of topics relevant to physics ranging from subatomic particles to all of the visible universe, majors have plenty to explore and learn. Physics majors should also plan to learn about the connections between physics and other sciences, such as astronomy, chemistry and biology.", 'img' => 'fisika.jpg'],

            ['name' => 'Gizi', 'trans-name'=> 'Nutrition', 'stream-science' => '1', 'stream-social' => '0', 'description' => "A nutrition major studies the relationship between nutrients in food and human health. Students with this major often can choose from multiple tracks and concentrations – such as general nutrition or nutritional sciences, public health or community nutrition, pre-medicine, or dietetics – depending on their career goals. Students with this major can become dietitians and nutritionists.", 'img' => 'gizi.jpg'],

            ['name' => 'Hubungan Internasional','trans-name'=> 'International Relations',  'stream-science' => '1', 'stream-social' => '1', 'description' => "An international relations major studies how the world works and the way politics, culture and economics impact the global system. Many programs require students to specialize in a certain theme, ranging from global security to human rights, and in a certain region of the world. Their knowledge base at the end of the program should reflect these emphases.

            At the end of the program, students should have a substantive understanding of the economic, political, cultural, historical and legal factors that influence international affairs. They should also be equipped to analyze current international events and communicate their analysis effectively in oral and written forms.", 'img' => 'hubungan internasional.jpg'],

            ['name' => 'Hukum', 'trans-name'=> 'Law', 'stream-science' => '1', 'stream-social' => '1', 'description' => "It may seem obvious, but what is law? Law, or legal studies, comes into contact with almost every area of human life, touching upon issues relating to business, economics, politics, the environment, human rights, international relations and trade. It is telling that the first academic degrees developed were all related to law. As a law student, you can expect to learn how to tackle some of the most problematic – indeed, often seemingly irresolvable – conflicts and issues in modern society and morality. In providing a framework through which to examine and understand different societies and cultures, law degrees are a useful way to prepare not only for specific legal careers, but for a broad range of professional roles – and indeed, for life in general.", 'img' => 'hukum.jpg'],

            ['name' => 'Ekonomi', 'trans-name'=> 'Economy', 'stream-science' => '1', 'stream-social' => '1', 'description' => "An economics major is a degree option that examines questions related to resource allocation, incentives and wealth, among others. Economics is relevant to graduate and professional study in fields like business management, law and public affairs, as well as undergraduate degrees that are useful for many career paths. Students often begin their studies by developing a solid foundation in microeconomics, macroeconomics and calculus, which they can use to pursue more advanced coursework and research opportunities. Those interested in the policy applications of economics may wish to enroll in classes that analyze real-world problems, while students considering a doctorate in economics should also explore some higher-level mathematics.", 'img' => 'ekonomi.jpg'],

            ['name' => 'Ilmu Komunikasi', 'trans-name'=> 'Communication Science', 'stream-science' => '1', 'stream-social' => '1', 'description' => "An economics major is a degree option that examines questions related to resource allocation, incentives and wealth, among others. Economics is relevant to graduate and professional study in fields like business management, law and public affairs, as well as undergraduate degrees that are useful for many career paths. Students often begin their studies by developing a solid foundation in microeconomics, macroeconomics and calculus, which they can use to pursue more advanced coursework and research opportunities. Those interested in the policy applications of economics may wish to enroll in classes that analyze real-world problems, while students considering a doctorate in economics should also explore some higher-level mathematics.", 'img' => 'ilmu komunikasi.jpg'],

            ['name' => 'Kedokteran', 'trans-name'=> 'Medical', 'stream-science' => '1', 'stream-social' => '0', 'description' => "A medical degree often takes years to complete but offers job security, a high average salary and the opportunity to save lives. Medical students can study in a speciality of their choosing, in many types of environments and often with new technology. The most successful medical students develop their scientific and interpersonal abilities simultaneously. ", 'img' => 'kedokteran.jpg'],

            ['name' => 'Kedokteran Gigi', 'trans-name'=> 'Dentistry', 'stream-science' => '1', 'stream-social' => '0', 'description' => "You'll take courses in natural sciences, such as biology, biochemistry, organic and inorganic chemistry, anatomy, physiology and physics. The curriculum for these programs can also help prepare you for the Dental Admissions Test, which is required for entry into dental school. You usually must maintain a minimum GPA of 2.0 in the pre-dentistry program in order to get into dental school. You'll be awarded a Bachelor of Science at the end of your pre-dentistry studies. ", 'img' => 'kedokteran gigi.jpg'],

            ['name' => 'Keperawatan', 'trans-name'=> 'Nursing', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Nursing emphasizes critical thinking, clinical judgment and service to others. Students in a nursing major can expect to explore the crossover between theoretical and practical learning. Students spend time in the classroom, studying the sciences, humanities, and the fundamentals of nursing and health care delivery. And they’ll apply this knowledge in the lab and during clinical components, where they’ll spend time learning the ins and outs of a career in nursing. A nursing major will prepare students to pursue different career paths in a variety of health care settings. Many work in clinical health care, like a hospital, doctor’s office or urgent care center. Some seek out leadership positions in a nursing administration role, while others head down a research path.", 'img' => 'keperawatan.jpg'],

            ['name' => 'Kimia', 'trans-name'=> 'Chemistry', 'stream-science' => '1', 'stream-social' => '0', 'description' => "A chemistry major explores the complex ways the elements on the periodic table combine. Those elements can produce table salt, a combination of sodium and chloride, water, a combination of hydrogen and oxygen, and myriad other, more complicated compounds. In classroom- and laboratory-based coursework, students will become adept problem-solvers as they learn fundamental properties of matter. Chemistry students can contribute to research related to cancer therapy, chemistry education and nutrient cycling, for example. Whether they go on to a career in research, medicine, business or another field, chemistry majors will be well-equipped to use their understanding of a science that affects daily life.", 'img' => 'kimia.jpg'],

            ['name' => 'Manajemen', 'trans-name'=> 'Management', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Management degrees give students a broad foundation in topics relating to business, finance, economics and marketing. Most management degrees have a very practical focus, with opportunities to complete work placements and professional projects included as part of the program. For those more interested in the theory which goes into informing policies and best practices in management, there are also more research-orientated management degrees to choose from. And, of course, programs that combine the two.", 'img' => 'manajemen.jpg'],

            ['name' => 'Matematika', 'trans-name'=> 'Mathematics', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Math majors study algebra, calculus, geometry and the different equations needed to solve problems. They also learn how to think and apply that foundation to an array of larger, more complex problems. German mathematician Carl Friedrich Gauss called mathematics 'the queen of the sciences,' since it sheds so much light on the physical reality. Some schools differentiate between pure mathematics and applied mathematics. One way to describe the difference between these two types of mathematics majors is that applied mathematics is math put to practical use, while pure mathematics is more of what you might see in the films 'Good Will Hunting' or 'A Beautiful Mind.' Put another way, pure mathematics is the study of mathematics without the primary motivation of outside applications.", 'img' => 'matematika.jpg'],
            
            ['name' => 'Psikologi', 'trans-name'=> 'Psychology', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Psychology is a skills-based major that can prepare students for graduate-level programs in psychology, education, law, medicine and business. It is a widely customizable major and is applicable to many careers. Students learn basic methods to conduct psychological research, reasoning and problem solving. After research is completed, students are expected to write papers on findings from experiments in the American Psychological Association, or APA, writing style, which calls for specific citation methods. Students will also understand the history of psychology by studying past experiments to learn from the earliest breakthroughs in the young field. Psychology majors will become very familiar with the theories of famous psychologists like Sigmund Freud, Albert Bandura, Ivan Pavlov, Wilhelm Wundt and others who shaped the science.", 'img' => 'psikologi.jpg'],

            ['name' => 'Sastra Inggris', 'trans-name'=> 'English Literature', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Whether you’re captivated by Chaucer’s Middle English poetics, obsessed with the colonial subtext in the novels of Joseph Conrad, or take a keen linguistic interest in the rap music of Snoop Dogg, you’ve come to the right place. This guide is all about what to expect from English language and literature degrees, including English topics you may be able to specialize in, opportunities for a journalism career, teaching career, or careers in the arts and humanities sectors, as well as the key skills you will pick up along the way.
            ", 'img' => 'sastra inggris.jpg'],

            ['name' => 'Sastra Jepang','trans-name'=> 'Japanese Literature',  'stream-science' => '1', 'stream-social' => '1', 'description' => "The Japanese Language & Literature major provides students with an appreciation and critical understanding of Japan’s rich literary and cultural traditions and contemporary culture along with a high level of proficiency (ACTFL intermediate-high) in the Japanese written and spoken language. The program also enables students to function effectively in cross-cultural contexts and to contribute meaningfully to the global challenges of today’s world.", 'img' => 'sastra jepang.jpg'],
            ['name' => 'Sistem Informasi', 'trans-name'=> 'Information Systems', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Information systems majors are prepared to solve problems at the intersection of business and technology. They explore ways to use various technology-based processes to help businesses and organizations operate more effectively and better serve their customers, staff and bottom line. To create and maintain innovative solutions, management information systems and services students rely on strong problem-solving, time-management and analytical skills.

            These majors are sometimes confused with computer science majors, but the two areas of study are unique. While computer science majors focus on creating software programs and are typically enrolled in mathematics departments or science and engineering schools, management information systems and services majors are more focused on organizing the connections between information, people and business operations. They’re typically business school students. ", 'img' => 'sistem informasi.jpg'],
            ['name' => 'Sosiologi', 'trans-name'=> 'Sociology', 'stream-science' => '1', 'stream-social' => '1', 'description' => "Sociology majors study society and human behavior. Sociology is a social science that analyzes human interactions, so students in this major study individuals, groups, communities, organizations, cultures and societies. They could look at interactions as small as two strangers at a coffee shop to something as large as globalization. Students not only focus on present-day interactions, but also cultures and societies throughout history.

            Students are trained to ask important questions, conduct research and collect data for analysis. Sociology majors apply their conclusions to address issues they've identified and improve key social processes. This could include addressing family conflict, religious discrimination and health care inequity.", 'img' => 'sosiologi.jpg'],

            ['name' => 'Statistika', 'trans-name'=> 'Statistics', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Statistics majors learn how to gather, analyze and interpret data. Students who choose this major might be interested in building careers in a number of other fields, such as government, banking or finance. Because statistics are relevant in myriad contexts, statistics majors can have wide-ranging interests.

            Passionate mathematicians who plan to go to graduate school can pursue more math-heavy coursework in Bachelor of Science programs, while students interested in practical applications might consider a Bachelor of Arts pathway. More than 160 institutions offer undergraduate degree programs in statistics, according to the U.S. News’ Best Colleges rankings, so students interested in the major should be able to explore plenty of options.", 'img' => 'statistika.jpg'],

            ['name' => 'Teknik Elektro', 'trans-name'=> 'Electrical Engineering', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Electrical engineers design, develop, and test electrical equipment. The broad field of electrical engineering involves working with all manners of electronic devices, from pocket calculators to supercomputers. Often overlapping with computer engineering, a college degree in electrical engineering can open up the door to a technical career in almost any industry. Since technology is always changing and expanding, the need for electrical engineers is always growing.", 'img' => 'teknik elektro.jpg'],

            ['name' => 'Teknik Industri', 'trans-name'=> 'Industrial Engineering', 'stream-science' => '1', 'stream-social' => '0', 'description' => "The focus of Industrial Engineering is how to improve processes or design things that are more efficient and waste less money, time, raw resources, man-power and energy while following safety standards and regulations. Industrial engineers may use knowledge of Maths, Physics but also Social Sciences to analyse, design, predict and evaluate the results and roadblocks of processes and devices. 

            Industrial engineers make sure your mobile phone fits in your pocket while still having a lot of processing power and also not overheating, or they can make sure it won't burst into flames while you're flying on a plane, for instance. As you can assume, there's a great need for capable industrial engineers in the world. 
            
            So, if a company's product isn't working as well as they had hoped, who're you gonna call? Industrial engineers!", 'img' => 'teknik industri.jpg'],

            ['name' => 'Teknik Kimia', 'trans-name'=> 'Chemical Engineering', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Ever wondered how materials like nylon and polyester are made? How it’s possible to make food stay fresh for longer? Or what happens inside a water treatment plant? Maybe you know all that, but are curious about how bionic plants, fog harvesting and carbon nanotubes can be used to improve the world around you. These are just some examples of topics you might cover as part of a chemical engineering degree – essentially the study of how to turn raw materials into useful, everyday (or perhaps more specialized) products.
            ", 'img' => 'teknik kimia.jpg'],

            ['name' => 'Teknik Mesin', 'trans-name'=> 'Mechanical Engineering', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Technically, mechanical engineering is the application of the principles and problem-solving techniques of engineering from design to manufacturing to the marketplace for any object. Mechanical engineers analyze their work using the principles of motion, energy, and force—ensuring that designs function safely, efficiently, and reliably, all at a competitive cost.

            Mechanical engineers make a difference. That's because mechanical engineering careers center on creating technologies to meet human needs. Virtually every product or service in modern life has probably been touched in some way by a mechanical engineer to help humankind.
            
            This includes solving today's problems and creating future solutions in health care, energy, transportation, world hunger, space exploration, climate change, and more. ", 'img' => 'teknik mesin.jpg'],

            ['name' => 'Teknik Sipil', 'trans-name'=> 'Civil Engineering', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Civil engineering is arguably the oldest engineering discipline. It deals with the built environment and can be dated to the first time someone placed a roof over his or her head or laid a tree trunk across a river to make it easier to get across.

            The built environment encompasses much of what defines modern civilization. Buildings and bridges are often the first constructions that come to mind, as they are the most conspicuous creations of structural engineering, one of civil engineering's major sub-disciplines. Roads, railroads, subway systems, and airports are designed by transportation engineers, another category of civil engineering.", 'img' => 'teknik sipil.jpg'],
            
            ['name' => 'Arsitektur', 'trans-name'=> 'Architecture', 'stream-science' => '1', 'stream-social' => '0', 'description' => "An architecture major learns the history and theory of the discipline, while also getting studio experience creating and planning their own architecture drafts.

            Students interested in pursuing an architecture major can typically choose from two types of programs: a five-year National Architectural Accrediting Board-accredited Bachelor of Architecture degree that equips graduates to enter the workforce or a four-year bachelor’s degree in architecture or architectural studies. With the latter, students have to earn an NAAB-accredited Master of Architecture degree to obtain a license and work as an architect. ", 'img' => 'arsitektur.jpg'],

            ['name' => 'Kedokteran Hewan', 'trans-name'=> 'Veterinary', 'stream-science' => '1', 'stream-social' => '0', 'description' => "If you are a patient and caring person who loves animals and feels comfortable around them, you may want to explore the educational and career options within the field of veterinary science and animal care.

            Veterinary scientists, technologists and technicians, as well as obedience trainers and even pet groomers, play a vital role in the maintenance and healthcare of pets, zoo animals, and livestock. In addition to meeting the healthcare and maintenance needs of animals, some individuals working in veterinary science use their skills to research diseases that also affect humans. For example, veterinary research played a significant role in conquering diseases such as yellow fever and malaria, and in understanding human heart disease, organ transplant procedures, and a variety of drug therapies.", 'img' => 'kedokteran hewan.jpg'],

            ['name' => 'Teknik Informatika', 'trans-name'=> 'Computer Science', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Computer science is a major for problem solvers who want to learn how to use computers and computational processes to build websites, program robots, mine data and more. Computer science majors may go on to master’s or doctorate programs in the field, and they can work in research and industry. Students will gain experience with the theory and practice of computer science as they explore algorithms, programming languages and operating systems, for example. In classes, majors may apply their learning to topics like computational finance, robotics and network security. Undergraduates may also be able to access research opportunities.", 'img' => 'teknik informatika.jpg'],

            ['name' => 'Teknologi Industri Pertanian', 'trans-name'=> 'Agricultural Systems Technology', 'stream-science' => '1', 'stream-social' => '0', 'description' => "Be it off-road equipment, agricultural machinery, food and grain processing, water quality, biofuels production, precision agriculture, or livestock production systems, an ag system technologist works to see how the individual pieces fit into the “big picture” of sustainability, conservation, and profitability.

            Agricultural Systems Technology (AST) graduates can find rewarding careers in a variety of agricultural and environmental businesses.  They focus on managing, using, and troubleshooting technology (instead of engineering design) by applying their knowledge of technology, agriculture, and processing systems.", 'img' => 'teknologi industri.jpg'],

            ['name' => 'Teknologi Pangan', 'trans-name'=> 'Food Technology', 'stream-science' => '1', 'stream-social' => '0', 'description' => "A program that focuses on the application of biological, chemical, and physical principles to the study of converting raw agricultural products into processed forms suitable for direct human consumption, and the storage of such products. Includes instruction in applicable aspects of the agricultural sciences, human physiology and nutrition, food chemistry, agricultural products processing, food additives, food preparation and packaging, food storage and shipment, and related aspects of human health and safety including toxicology and pathology. ", 'img' => 'teknologi pangan.jpg'],
        ]);
    }
}
